### ISSUE TITLE
Unable to Add Virtual Motion Sensor

### ISSUE THREAD

**Issue by jscongdon** [nutechsoftware/alarmdecoder-smartthings#45]
When trying to add the Virtual Motion Sensor from the repository I get the following message:

> Updated 0 devices and created 0 new devices, 0 published (1 skipped due to errors)

I am able to add it manually, though. Doing so does not link to the repo and then will not update. You can change the repository that it belongs to but am unsure if it will update when needed.

**Comment by f34rdotcom** [comment]
I saw the same problem and fixed it the same way a few weeks back. I will see if I can figure out why. Very odd error. The code seems fine but github integration is confused.

**Comment by f34rdotcom** [comment]
Ok fixed in dev. It was the name. It has to somewhat match the file name.
Thanks!

**Comment by jscongdon** [comment]
Still unable to import the DH.
Would it have anything to do with the author tag in the metadata?

**Comment by f34rdotcom** [comment]
I deleted mine again and reloaded from dev branch and it is not throwing me an error. I still see plenty wrong with this module as noted in the metadata but AFAIK the only real complaint was that the file name must match the device name with spaces will be sub with '_' and case is not important.

**Comment by f34rdotcom** [comment]
FWIW the dev branch is about to get really crazy so as you noted that issue in the meta data I plan on going over every part and doing a cleanup/tidy.

**Comment by jscongdon** [comment]
Weird. I was able to load the dev.
From what I can tell the src file name is the same for dev and master. IDK. That's for the hard work.
